# Cloudflare Workers Configuration
name = "ocaml-portfolio"
main = "src/index.ts"
compatibility_date = "2024-01-01"
workers_dev = true

# Modern static assets - NO KV namespaces needed!
[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"

[env.production]
name = "ocaml-portfolio"
# Enable workers.dev subdomain for testing
workers_dev = false
routes = ["arnabb.dev/*", "www.arnabb.dev/*"]

# Assets configuration for production
[env.production.assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"

# Preview/staging environment
[env.preview]
name = "ocaml-portfolio-preview"
workers_dev = true

# Development environment configuration
[dev]
port = 8080
local_protocol = "http"

# wrangler.toml (wrangler v4.0.0^)
[observability.logs]
enabled = false
