# Cloudflare Pages Configuration
name = "ocaml-portfolio"
compatibility_date = "2024-01-01"

# Build configuration
[build]
command = "opam exec -- make build-prod && npm run build:cloudflare"
publish = "dist"

# Build environment variables
[build.environment]
NODE_VERSION = "20"

# Preview builds
[preview]
command = "opam exec -- make build-prod && npm run build:cloudflare"

# Environment variables
[env.production]
vars = { ENVIRONMENT = "production" }

[env.preview]
vars = { ENVIRONMENT = "preview" }