# Cloudflare Workers Configuration
name = "ocaml-portfolio"
main = "src/index.ts"
compatibility_date = "2024-01-01"
workers_dev = true

# Serve static assets from dist directory
[site]
bucket = "./dist"

# Build configuration for local development
[build]
command = "npm run build:worker"

[env.production]
name = "ocaml-portfolio-prod"
workers_dev = false
# Routes will be configured in Cloudflare dashboard or via API

# Preview/staging environment
[env.preview]
name = "ocaml-portfolio-preview"
workers_dev = true

# Development environment configuration
[dev]
port = 8080
local_protocol = "http"
