# Cloudflare Workers Configuration
name = "ocaml-portfolio"
main = "src/index.ts"
compatibility_date = "2024-01-01"
workers_dev = true

# Serve static assets from dist directory
[site]
bucket = "./dist"

# Build configuration for local development
[build]
command = "npm run build:worker"

[env.production]
workers_dev = false
routes = ["arnabb.dev/*", "www.arnabb.dev/*"]

# Preview/staging environment
[env.preview]
name = "ocaml-portfolio-preview"
workers_dev = true

# Development environment configuration
[dev]
port = 8080
local_protocol = "http"
