name: Deploy OCaml Portfolio to Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5.2.1

      - name: System deps
        run: |
          sudo apt-get update
          sudo apt-get install -y m4 pkg-config libgmp-dev

      - name: Install opam deps
        run: opam install . --deps-only -y

      - name: Build (production)
        run: opam exec -- make build-prod

      # -- Assemble exactly what index.html expects --
      - name: Assemble Pages artifact
        run: |
          echo "=== Creating artifact structure ==="
          mkdir -p _site/_build/default/lib/client_main
          mkdir -p _site/static
          
          echo "=== Copying index.html ==="
          cp static/index.html _site/index.html
          
          echo "=== Copying 404.html for GitHub Pages fallback ==="
          cp static/404.html _site/404.html
          
          echo "=== Copying resume.pdf explicitly ==="
          cp static/resume.pdf _site/static/resume.pdf
          
          echo "=== Finding and copying JS bundle ==="
          JS_PATH=$(find _build -type f -path '*/lib/client_main/main.bc.js' | head -n1)
          if [ -z "$JS_PATH" ]; then
            echo "ERROR: main.bc.js not found. Check your dune/js_of_ocaml output path."
            exit 1
          fi
          echo "Found JS at: $JS_PATH"
          cp "$JS_PATH" _site/_build/default/lib/client_main/main.bc.js
          
          echo "=== Final artifact structure ==="
          find _site -type f -ls
          echo "=== Verifying critical files ==="
          test -f _site/index.html && echo "✓ index.html present" || echo "✗ index.html MISSING"
          test -f _site/404.html && echo "✓ 404.html present" || echo "✗ 404.html MISSING"
          test -f _site/static/resume.pdf && echo "✓ resume.pdf present" || echo "✗ resume.pdf MISSING"
          test -f _site/_build/default/lib/client_main/main.bc.js && echo "✓ main.bc.js present" || echo "✗ main.bc.js MISSING"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
